### ISSUE TITLE
Cannot receive input changes on Windows 10

### ISSUE THREAD

**Issue by jacovig** [oakes/Lightmod#5] opened 2017-12-01 11:37 UTC
I cannot see the :on-change changes in lightmod but it works well when you open the app with any browser.

On macos it works correctly.

Btw, WONDERFULL work. I only have a bit or trouble with parens but edit files with bbedit (or notepad++ on windows).

**Comment by oakes** [comment] 2017-12-01 14:58
You mean the even doesn't fire at all in the built-in webview? I'll take a look, thank you for reporting it.

**Comment by jacovig** [comment] 2017-12-01 18:49
It seems so. It works in the built-in webview on Mac but not on Windows. It
works in the web browser in both.
It seems that it doesn't fire at all by I could not say for sure.

This is the full code of client.js:

Regards.

(ns amigo.client
  (:require [reagent.core :as r]
            [taoensso.sente :as sente]))

; sets up various things for the chat server
(defonce socket (sente/make-channel-socket! "/amigo" {:type :auto}))
(def ch-chsk (:ch-recv socket))
(def chsk-send! (:send-fn socket))

; store the keys
(defonce clave_tmp (r/atom "nada"))

; runs when a message is received
(defn event-msg-handler
  [{:keys [id ?data event]}]
  (case id
    :chsk/recv
    (case (first ?data)
      ; :amigo/message
      ; (swap! messages conj (second ?data)))
    nil))


; reagent component to be rendered
(defn content []
  [:div
   [:input {:type "text"
             :value @clave_tmp
             :on-change #(reset! clave_tmp (-> % .-target .-value))}]
   [:p "Valor : " @clave_tmp]
   ])

; tells reagent to begin rendering
(r/render-component [content]
  (.querySelector js/document "#app"))

; connects to the server
(sente/start-client-chsk-router! ch-chsk event-msg-handler)

**Comment by oakes** [comment] 2019-12-21 21:34
Closing because I can't reproduce on the latest version; this was probably fixed when I updated javafx. I'm now using javafx 13 and jdk 11.

**Closed as completed by oakes** 2019-12-21 21:34 UTC
